# MONAI label

MONAI Label is an intelligent open source image labeling and learning tool that enables users to create annotated datasets and build AI annotation models for clinical evaluation. MONAI Label enables application developers to build labeling apps in a serverless way, where custom labeling apps are exposed as a service through the MONAI Label Server.

## configuration

In [ ]:
#check work directory
!pwd

### check available MONAI Label Apps.

In [ ]:
# check available apps
!monailabel apps

### download radiology and pathology example script

In [ ]:
!monailabel apps --download --name radiology --output apps
!monailabel apps --download --name pathology --output apps

### Download available Dataset

In [ ]:
# check available  sample Datasets
!monailabel datasets # List sample datasets


#### download sample dataset for segmentation 

In [ ]:
!monailabel datasets --download --name Task09_Spleen --output datasets
!monailabel datasets --download --name Task06_Lung  --output datasets

In [ ]:
!monailabel datasets --download --name Task09_Spleen --output datasets
!monailabel datasets --download --name Task06_Lung  --output datasets

# launch monai app server

## check allocated port for 9999 port

In [28]:
!cat ~/port_forwarding_command

ssh -L localhost:8888:dgx07:8840 -L localhost:9999:dgx07:9840 ssh.axisapps.io -l 88d94f68f53d4beebaa9090b02bcb23d



#### for example, 
if the port_forwarding_command is below : 
```
ssh -L localhost:8888:dgx05:8730 -L localhost:9999:dgx05:9730 ssh.axisapps.io -l 9bffbbd44d83471292ec7189545006fd
```

check `-L localhost:9999:dgx05:9730` 


- PORT number :  `9730`
- app  : `~/workspace-monailabel-labs/apps/radiology`
- studies :  `~/workspace-monailabel-labs/dataset/Task09_Spleen/imagesTr`
- configure model : segmentation_spleen 

```
monailabel start_server --app  ~/workspace-monailabel-labs/apps/radiology  --studies  ~/workspace-monailabel-labs/datasets/Task09_Spleen/imagesTr --conf models segmentation_spleen --host 0.0.0.0 --port 9730 --verbose DEBUG
```

### launch monai label server ( lung segment)

- step1. copy command ( Control + C)  
- step2. open New terminal 
- step3. (Control + V) in terminal 
- step4. reload and reaccess server in 3D Slicer 

```monailabel start_server --app  ~/workspace-monailabel-labs/apps/radiology  --studies  ~/workspace-monailabel-labs/datasets/Task09_Spleen/imagesTr --conf models segmentation_spleen --host 0.0.0.0 --port 9730 --verbose DEBUG```

In [29]:
!monailabel start_server --app  /lustre/workspaces/f3mx6wqa/workspace-monailabel-labs/apps/radiology  --studies  /lustre/workspaces/f3mx6wqa/workspace-monailabel-labs/datasets/Task09_Spleen/imagesTr --conf models segmentation_spleen --host 0.0.0.0 --port 9840 --verbose DEBUG

Using PYTHONPATH=/opt:
[2022-11-05 06:43:22,987] [3158870] [MainThread] [INFO] (__main__:269) - USING:: app = /lustre/workspaces/f3mx6wqa/workspace-monailabel-labs/apps/radiology
[2022-11-05 06:43:22,987] [3158870] [MainThread] [INFO] (__main__:269) - USING:: studies = /lustre/workspaces/f3mx6wqa/workspace-monailabel-labs/datasets/Task09_Spleen/imagesTr
[2022-11-05 06:43:22,987] [3158870] [MainThread] [INFO] (__main__:269) - USING:: verbose = DEBUG
[2022-11-05 06:43:22,987] [3158870] [MainThread] [INFO] (__main__:269) - USING:: conf = [['models', 'segmentation_spleen']]
[2022-11-05 06:43:22,987] [3158870] [MainThread] [INFO] (__main__:269) - USING:: host = 0.0.0.0
[2022-11-05 06:43:22,987] [3158870] [MainThread] [INFO] (__main__:269) - USING:: port = 9840
[2022-11-05 06:43:22,987] [3158870] [MainThread] [INFO] (__main__:269) - USING:: uvicorn_app = monailabel.app:app
[2022-11-05 06:43:22,987] [3158870] [MainThread] [INFO] (__main__:269) - USING:: ssl_keyfile = None
[2022-11-05 06:43:22

### launch monai label server ( deepedit)

- step1. copy command ( Control + C)
- step2. open New terminal
- step3. (Control + V) in terminal
- step4. reload and reaccess server in 3D Slicer

```monailabel start_server --app  ~/workspace-monailabel-labs/apps/radiology  --studies  ~/workspace-monailabel-labs/datasets/Task09_Spleen/imagesTr --conf models deepedit --host 0.0.0.0 --port 9730 --verbose DEBUG```

In [ ]:
monailabel start_server --app  /lustre/workspaces/f3mx6wqa/workspace-monailabel-labs/apps/radiology  --studies  /lustre/workspaces/f3mx6wqa/workspace-monailabel-labs/datasets/Task09_Spleen/imagesTr --conf models deepedit --host 0.0.0.0 --port 9840 --verbose DEBUG

### launch monai label server ( deepgrow_3d)

- step1. copy command ( Control + C)
- step2. open New terminal
- step3. (Control + V) in terminal
- step4. reload and reaccess server in 3D Slicer

```monailabel start_server --app  ~/workspace-monailabel-labs/apps/radiology  --studies  ~/workspace-monailabel-labs/datasets/Task09_Spleen/imagesTr --conf models deepgrow_3d --host 0.0.0.0 --port 9730 --verbose DEBUG```

In [ ]:
# monailabel start_server --app  ~/workspace-monailabel-labs/apps/radiology  --studies  ~/workspace-monailabel-labs/datasets/Task09_Spleen/imagesTr --conf models deepgrow_3d --host 0.0.0.0 --port 9730 --verbose DEBUG

### launch monai label server ( custom model segmentation_lung)

dataset lung 
- step0. copy `apps/libs/configs/segmentation.py` to new `segmentation_lung.py` 
- step1. open and edit label `right lung:1` , `left lung:2` , `airways:3` 
- step2. edit configure  `"use_pretrained_model", "false"` and save
- step3. copy command ( Control + C)
- step4. open New terminal
- step5. (Control + V) in terminal
- step6. reload and reaccess server in 3D Slicer

```monailabel start_server --app  ~/workspace-monailabel-labs/apps/radiology  --studies  ~/workspace-monailabel-labs/datasets/Task06_Lung/imagesTr --conf models segmentation_lung --host 0.0.0.0 --port 9730 --verbose DEBUG```

In [ ]:
!monailabel start_server --app  /lustre/workspaces/f3mx6wqa/workspace-monailabel-labs/apps/radiology  --studies  ~/workspace-monailabel-labs/datasets/Task09_Spleen/imagesTr --conf models deepgrow_3d --host 0.0.0.0 --port 9730 --verbose DEBUG

In [ ]:
!monailabel start_server --app  /opt/conda/monailabel/sample-apps/radiology  --studies  ~/workspace-monailabel-labs/datasets/Task09_Spleen/imagesTr --conf models deepedit --host 0.0.0.0 --port 9730 --verbose DEBUG

In [ ]:
!monailabel start_server --app  ~/workspace-monailabel-labs/apps/radiology  --studies  ~/workspace-monailabel-labs/datasets/Task09_Spleen/imagesTr --conf models segmentaion --host 0.0.0.0 --port 9730 --verbose DEBUG